import { getDB } from '../memory/store.js';
import { v4 as uuidv4 } from 'uuid';

/**
 * Logs a skill execution event to the database.
 * @param {string} skillName - Name of the executed skill.
 * @param {number} trustTier - Trust tier level of the skill.
 * @param {Object} inputs - Inputs provided to the skill.
 * @param {Object|string} outputs - Output generated by the skill.
 * @param {number} durationMs - Execution time in milliseconds.
 */
export function logSkillExecution(skillName, trustTier, inputs, outputs, durationMs) {
  try {
    const db = getDB();
    const id = uuidv4();
    const sql = `
      INSERT INTO skill_audit_logs (id, skill_name, trust_tier, inputs, outputs, duration_ms)
      VALUES (?, ?, ?, ?, ?, ?)
    `;
    const params = [
      id,
      skillName,
      trustTier,
      JSON.stringify(inputs),
      typeof outputs === 'string' ? outputs : JSON.stringify(outputs),
      durationMs
    ];

    db.prepare(sql).run(...params);
  } catch (err) {
    console.error(`[Audit] Failed to log skill execution for ${skillName}:`, err.message);
  }
}

/**
 * Retrieves the most recent skill execution logs.
 * @param {number} limit - The maximum number of logs to retrieve.
 * @returns {Array<Object>} List of audit log entries.
 */
export function getSkillAuditLogs(limit = 50) {
  try {
    const db = getDB();
    return db.prepare('SELECT * FROM skill_audit_logs ORDER BY timestamp DESC LIMIT ?').all(limit);
  } catch (err) {
    console.error('[Audit] Failed to retrieve skill audit logs:', err.message);
    return [];
  }
}
